### ISSUE TITLE
Problems on ARGPARSE

### ISSUE THREAD

**Issue by carlosdbez** [andywu0913/OpenAI-GYM-CarRacing-DQN#2]
Hello. Congratulations on the development of DQN.

I am an engineering student and would like to do your coding.

I'm having trouble running play_car_racing_by_the_model.py

I am not understanding the parameters to initialize the code:

play_car_racing_by_the_model.py [-h] -m 'save / trial_300.h5' [-e 1]

-m is a string? I am putting the save folder path though it is giving invalid syntax.

Please, could you help me ??

![image](https://user-images.githubusercontent.com/75349772/100824696-740f4180-3435-11eb-991f-aac3827fead4.png)

**Comment by andywu0913** [comment]
Seems like you are executing the command in the python interactive shell mode.

The commands in README.md should be executed from the system command not python.
What I mean is if you are using Windows just simply open cmd, paste the command and hit enter.
If on a Mac, open the terminal in Launchpad, paste the command and hit enter.

As long as your python is installed correctly and the necessary files exist, you should be able to see the program running:)

**Comment by carlosdbez** [comment]
Thanks for the feedback

Thanks!
After some configuration in the cmd patch the program ran.

Just one more question, does it have any function to generate e-greedy graphics?

**Comment by andywu0913** [comment]
You mean like the 3rd graph in the training result from README.md?

I record all the hyperparameter changes during training and drew it with matplotlib package by myself.
